# Generated by Django 5.1.1 on 2024-11-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador Academico'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], default='estudiante', max_length=15),
        ),
    ]
