# Generated by Django 5.1.1 on 2024-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(max_length=50),
        ),
    ]
